#!/usr/bin/env python3
"""Build a dependency-free, bilingual static site. Run from any directory."""
from pathlib import Path
from hashlib import sha256
from html import escape
from base64 import b64encode
import json

ROOT = Path(__file__).resolve().parents[1]
DOMAIN = 'https://radapps.app'
DATE = '2026-09-17'
PAGE_MODIFIED = {'home': '2026-09-20'}
EMAIL = 'admin@alvaro-menezes.com'
PAGES = {
    'home': ('', '', 'RadApps — Aplicativos e calculadoras para Radiologia', 'RadApps — Radiology Apps and Medical Calculators'),
    'terms': ('termos/', 'terms/', 'Termos de uso', 'Terms of use'),
    'privacy': ('privacidade/', 'privacy/', 'Política de privacidade', 'Privacy policy'),
    'cookies': ('cookies/', 'cookies/', 'Cookies e preferências', 'Cookies and preferences'),
    'medical': ('aviso-medico/', 'medical-disclaimer/', 'Aviso médico', 'Medical disclaimer'),
    'accessibility': ('acessibilidade/', 'accessibility/', 'Acessibilidade', 'Accessibility'),
}
APPS = [
    ('puberty','Puberty Calc','US pélvica pediátrica: maturação puberal e laudo (PT/EN)','Pediatric pelvic ultrasound: pubertal maturation and report (PT/EN)'),
    ('gfr','GFR','Filtração glomerular: CKD-EPI, CKiD U25 e Schwartz','Glomerular filtration: CKD-EPI, CKiD U25 and Schwartz'),
    ('tirads','TI-RADS','Calcula o TI-RADS na Ultrassonografia da Tireoide','Calculates TI-RADS on thyroid ultrasound'),
    ('hepfe','HepFe*','Quantificação do ferro hepático por RM','Liver iron quantification by MRI'),
    ('orads','O-RADS Calc','Classificação de lesões anexiais em US e RM','Adnexal lesions on ultrasound and MRI'),
    ('nlung','N-Lung Calc','Recomendações Fleischner e Lung-RADS','Fleischner and Lung-RADS recommendations'),
]
APP_GUIDES = {
    'puberty': (
        'Puberty Calc: ultrassonografia pélvica pediátrica', 'Puberty Calc: pediatric pelvic ultrasound',
        'Integra idade, história de menarca e medidas da pelve feminina por via transabdominal. Calcula volumes e relação fundo/colo, apresenta uma estimativa descritiva do padrão puberal e gera uma minuta de laudo com conclusão. Os critérios e limites são explicitados; a ferramenta não confirma puberdade precoce nem atribui estágio de Tanner.',
        'Combines age, menarche history and transabdominal female pelvic measurements. Calculates volumes and the fundus-to-cervix ratio, offers a descriptive estimate of pubertal morphology and generates a draft report with a conclusion. Criteria and limitations are explicit; the tool does not diagnose precocious puberty or assign a Tanner stage. The interface and report are available in Portuguese and English.'),
    'gfr': (
        'GFR: cálculo da função renal', 'GFR: kidney function calculator',
        'Estima a taxa de filtração glomerular a partir da creatinina e dos dados exigidos pela equação. Reúne CKD-EPI 2021, CKiD U25 e Schwartz, com escolha do método conforme a faixa etária. As referências e limitações de cada estimativa estão disponíveis no aplicativo.',
        'Estimates glomerular filtration rate from creatinine and the inputs required by each equation. Includes CKD-EPI 2021, CKiD U25 and Schwartz, with method selection according to age. References and limitations for each estimate are available in the app.'),
    'tirads': (
        'TI-RADS: nódulos da tireoide', 'TI-RADS: thyroid nodules',
        'Organiza os achados dos nódulos tireoidianos na ultrassonografia segundo o ACR TI-RADS. Permite revisar pontuação, categoria e orientações relacionadas às medidas e ao contexto informado, além de preparar uma descrição para revisão profissional.',
        'Organises thyroid nodule ultrasound findings using ACR TI-RADS. Review the score, category and guidance related to the measurements and context entered, and prepare a description for professional review.'),
    'hepfe': (
        'HepFe: ferro hepático por ressonância', 'HepFe: liver iron by MRI',
        'Analisa o decaimento do sinal em medidas de ressonância magnética para estimar ferro hepático. Oferece ajuste da curva, escolha de calibração e exportação de gráfico e texto para revisão. A interpretação depende da aquisição, do modelo utilizado e de suas limitações.',
        'Analyses signal decay in MRI measurements to estimate liver iron. Provides curve fitting, calibration selection and export of a plot and text for review. Interpretation depends on the acquisition, the chosen model and its limitations.'),
    'orads': (
        'O-RADS: lesões ovarianas e anexiais', 'O-RADS: ovarian and adnexal lesions',
        'Auxilia a organizar os descritores de uma lesão anexial em ultrassonografia ou ressonância magnética segundo o ACR O-RADS. O aplicativo apresenta categoria, referências e texto de laudo para revisão, respeitando a modalidade e o contexto de aplicação.',
        'Helps organise descriptors for an adnexal lesion on ultrasound or MRI using ACR O-RADS. The app presents the category, references and draft report text for review, with attention to the imaging modality and applicable clinical context.'),
    'nlung': (
        'N-Lung: nódulos pulmonares na tomografia', 'N-Lung: pulmonary nodules on CT',
        'Separa a avaliação de nódulos incidentais pelas recomendações Fleischner da avaliação de rastreamento pelo Lung-RADS. Reúne medidas, comparação entre exames e texto de laudo para revisão. Confira os critérios de aplicabilidade antes de usar cada sistema.',
        'Separates incidental nodule assessment using Fleischner recommendations from screening assessment using Lung-RADS. Brings together measurements, examination comparison and draft report text for review. Check the eligibility criteria before using each system.'),
}
LEGAL_DESCRIPTIONS = {
    'terms': ('Termos de uso do site RadApps: finalidade, acesso, aplicativos vinculados, propriedade intelectual e contato do responsável.', 'RadApps website terms: purpose, access, linked applications, intellectual property and operator contact details.'),
    'privacy': ('Privacidade na RadApps: dados de navegação, Cloudflare Web Analytics, armazenamento local, contato e direitos dos titulares.', 'Privacy at RadApps: browsing data, Cloudflare Web Analytics, local storage, contact details and data subject rights.'),
    'cookies': ('Cookies e preferências da RadApps: armazenamento do tema, medição de visitas, infraestrutura e como redefinir suas preferências.', 'RadApps cookies and preferences: theme storage, visitor measurement, infrastructure and how to reset your preferences.'),
    'medical': ('Aviso médico da RadApps: público profissional, limites das calculadoras, revisão dos resultados e uso responsável das ferramentas.', 'RadApps medical disclaimer: professional audience, calculator limitations, result review and responsible use of the tools.'),
    'accessibility': ('Acessibilidade na RadApps: navegação por teclado, leitura, contraste, preferências visuais e canal para comunicar dificuldades.', 'Accessibility at RadApps: keyboard navigation, readability, contrast, display preferences and how to report access difficulties.'),
}
def asset(path):
    return '/assets/' + path + '?v=' + sha256((ROOT/'assets'/path).read_bytes()).hexdigest()[:12]
def url(page, lang):
    return ('/en/' if lang else '/') + PAGES[page][lang]
def title(page, lang):
    return PAGES[page][lang+2]
def svg(kind):
    paths = {
        'phone': '<rect x="6" y="2" width="12" height="20" rx="3"/><path d="M10 18h4M10 5h4"/>',
        'android': '<path d="m7 5-2-3m12 3 2-3M4 12a8 8 0 0 1 16 0v7H4zM8 19v3m8-3v3M1 12v5m22-5v5"/><path d="M8 9h.01M16 9h.01"/>',
        'web': '<rect x="2" y="3" width="20" height="16" rx="2"/><path d="M2 8h20M8 5.5h.01M5 5.5h.01m5 6-2 2 2 2m4-4 2 2-2 2"/>',
        'sun': '<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',
        'moon': '<path d="M20.5 13.2A9 9 0 0 1 10.8 3.5 9 9 0 1 0 20.5 13.2Z"/>',
    }
    return f'<svg class="{kind}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{paths[kind]}</svg>'
def shell(page, lang, content, description=None, not_found=False):
    t = lambda pt,en: en if lang else pt
    home = url('home', lang)
    langcode = 'en' if lang else 'pt-BR'
    page_title = title(page,lang) + ('' if page == 'home' else ' | RadApps')
    if not_found:
        page_title = 'Página não encontrada | RadApps'
    description = description or t('Aplicativos e calculadoras para radiologia: Puberty Calc, TI-RADS, O-RADS, GFR, HepFe e N-Lung. Conheça a RadApps, iniciativa do radiologista Dr. Álvaro Menezes.','Radiology apps and medical calculators: Puberty Calc, TI-RADS, O-RADS, GFR, HepFe and N-Lung. Discover RadApps, created by radiologist Dr. Álvaro Menezes.')
    links = [('sobre',t('Sobre','About')),('aplicativos',t('Aplicativos','Apps')),('plataformas',t('Plataformas','Platforms')),('duvidas',t('Dúvidas','FAQ')),('contato',t('Contato','Contact'))]
    nav = ''.join(f'<li><a {"class=nav-contact" if key=="contato" else ""} href="{home}#{key}">{label}</a></li>' for key,label in links)
    legal_links = ''.join(f'<a href="{url(key,lang)}">{title(key,lang)}</a>' for key in PAGES if key != 'home')
    page_url = DOMAIN + ('/404.html' if not_found else url(page,lang))
    alternates = '' if not_found else ''.join(
        f'<link rel="alternate" hreflang="{code}" href="{DOMAIN}{url(page,language)}">'
        for code,language in [('pt-BR',0),('en',1),('x-default',0)])
    schema = {'@context':'https://schema.org', '@graph':[
        {'@type':'Organization', '@id':DOMAIN+'/#organization', 'name':'RadApps', 'url':DOMAIN+'/',
         'logo':DOMAIN+'/assets/brand/radapps-logo.jpg', 'email':EMAIL,
         'description':t('Iniciativa independente de desenvolvimento de aplicativos para radiologia.','Independent radiology application development initiative.'),
         'founder':{'@id':'https://alvaro-menezes.com/#person'}},
        {'@type':'Person', '@id':'https://alvaro-menezes.com/#person', 'name':'Álvaro Menezes', 'url':'https://alvaro-menezes.com/'},
        {'@type':'WebSite', '@id':DOMAIN+'/#website', 'name':'RadApps', 'url':DOMAIN+'/',
         'inLanguage':['pt-BR','en'], 'publisher':{'@id':DOMAIN+'/#organization'}},
        {'@type':'WebPage', '@id':page_url+'#webpage', 'url':page_url, 'name':page_title,
         'description':description, 'inLanguage':langcode, 'isPartOf':{'@id':DOMAIN+'/#website'}},
    ]}
    if page == 'home' and not not_found:
        schema['@graph'][-1]['mainEntity'] = {'@id':page_url+'#apps'}
        schema['@graph'].append({'@type':'ItemList', '@id':page_url+'#apps',
            'name':t('Aplicativos para o Radiologista','Apps for the Radiologist'),
            'numberOfItems':len(APPS), 'itemListElement':[
                {'@type':'ListItem', 'position':i, 'item':{'@type':'WebPage',
                 'name':name, 'description':en if lang else pt,
                 'url':f'https://alvaro-menezes.com/apps/{slug}.html'}}
                for i,(slug,name,pt,en) in enumerate(APPS,1)]})
    elif not not_found:
        schema['@graph'][-1]['breadcrumb'] = {'@id':page_url+'#breadcrumb'}
        schema['@graph'].append({'@type':'BreadcrumbList', '@id':page_url+'#breadcrumb',
            'itemListElement':[
                {'@type':'ListItem', 'position':1, 'name':'RadApps', 'item':DOMAIN+home},
                {'@type':'ListItem', 'position':2, 'name':title(page,lang), 'item':page_url},
            ]})
    schema_text = json.dumps(schema,ensure_ascii=False)
    schema_hash = b64encode(sha256(schema_text.encode()).digest()).decode()
    return f'''<!doctype html>
<html lang="{langcode}"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(page_title)}</title><meta name="description" content="{escape(description)}">
<meta name="robots" content="{'noindex, follow' if not_found else 'index, follow, max-image-preview:large'}">
<meta name="author" content="RadApps · Álvaro Menezes"><meta name="theme-color" content="#0a2540">
<meta name="referrer" content="strict-origin-when-cross-origin">
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'sha256-{schema_hash}' https://static.cloudflareinsights.com; style-src 'self'; img-src 'self'; font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'self'; form-action 'none'">
<link rel="canonical" href="{page_url}">
{alternates}
<meta property="og:type" content="website"><meta property="og:site_name" content="RadApps"><meta property="og:title" content="{escape(page_title)}"><meta property="og:description" content="{escape(description)}"><meta property="og:url" content="{page_url}"><meta property="og:locale" content="{'en_US' if lang else 'pt_BR'}"><meta property="og:image" content="{DOMAIN}/assets/brand/radapps-banner.jpg"><meta property="og:image:width" content="1792"><meta property="og:image:height" content="1008"><meta property="og:image:alt" content="RadApps — Apps for radiologists. Built for precision."><meta name="twitter:card" content="summary_large_image">
<meta property="og:locale:alternate" content="{'pt_BR' if lang else 'en_US'}"><meta name="twitter:title" content="{escape(page_title)}"><meta name="twitter:description" content="{escape(description)}"><meta name="twitter:image" content="{DOMAIN}/assets/brand/radapps-banner.jpg"><meta name="twitter:image:alt" content="RadApps — Apps for radiologists. Built for precision.">
<link rel="icon" type="image/jpeg" href="/assets/brand/radapps-logo.jpg"><link rel="apple-touch-icon" href="/assets/brand/radapps-logo.jpg">
<link rel="preload" href="/assets/fonts/inter-latin.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/assets/fonts/playfair-latin.woff2" as="font" type="font/woff2" crossorigin>
<script src="{asset('theme-init.js')}"></script><link rel="stylesheet" href="{asset('site.css')}">
<script type="application/ld+json">{schema_text}</script><script src="{asset('site.js')}" defer></script>
</head><body>
<a class="skip-link" href="#conteudo">{t('Pular para o conteúdo','Skip to content')}</a>
<header class="site-header"><div class="topbar"><div class="container topbar-inner"><div class="preferences"><nav class="language-switch" aria-label="Idioma / Language"><a href="{url(page,0)}" lang="pt-BR" hreflang="pt-BR" aria-label="Português" aria-current="{str(not lang).lower()}">PT</a><a href="{url(page,1)}" lang="en" hreflang="en" aria-label="English" aria-current="{str(bool(lang)).lower()}">EN</a></nav><button class="theme-toggle" type="button" aria-label="{t('Mudar tema','Change theme')}">{svg('moon')}{svg('sun')}</button></div><span class="topbar-note">{t('RADIOLOGIA, TECNOLOGIA E PRECISÃO','RADIOLOGY, TECHNOLOGY & PRECISION')}</span></div></div>
<nav class="navbar" aria-label="{t('Navegação principal','Main navigation')}"><div class="container nav-inner"><a class="brand" href="{home}" aria-label="{t('RadApps — início','RadApps — home')}"><img src="/assets/brand/radapps-logo.jpg" width="58" height="58" alt=""><span><span class="brand-name">Rad<span>Apps</span></span><span class="brand-caption">Apps for radiologists</span></span></a><button class="menu-toggle" aria-controls="nav-links" aria-expanded="false" type="button">Menu <span aria-hidden="true">☰</span></button><ul class="nav-links" id="nav-links">{nav}</ul></div></nav></header>
<main id="conteudo">{content}</main>
<aside class="legal-ribbon"><div class="container"><p>{t('Ferramentas de referência para profissionais de saúde. Resultados devem ser conferidos com as fontes e o contexto clínico. Não substituem avaliação médica.','Reference tools for healthcare professionals. Check results against source guidance and clinical context. They do not replace medical assessment.')} <a href="{url('medical',lang)}">{t('Leia o aviso médico','Read the medical disclaimer')} ↗</a></p></div></aside>
<footer class="footer"><div class="container"><div class="footer-main"><div><a class="footer-brand" href="{home}">RadApps<span style="display:none"></span></a><p class="footer-tagline">Apps for radiologists.<br>Built for precision.</p></div><nav class="footer-links" aria-label="{t('Informações legais','Legal information')}">{legal_links}</nav></div><div class="footer-bottom"><p>© 2026 RadApps · {t('Uma iniciativa de Álvaro Menezes.','An initiative by Álvaro Menezes.')}</p><p><a href="https://alvaro-menezes.com/" target="_blank" rel="noopener noreferrer">Dr. Álvaro Menezes ↗</a> &nbsp; · &nbsp; <a href="{home}#inicio">{t('Voltar ao início','Back to top')} ↑</a></p></div></div></footer>
</body></html>'''.replace('<span style="display:none"></span>','')

def homepage(lang):
    t = lambda pt,en: en if lang else pt
    apps = ''.join(f'''<a class="app-tile" href="https://alvaro-menezes.com/apps/{slug}.html" target="_blank" rel="noopener noreferrer"><span class="app-icon"><img src="{asset(f'apps/{slug}-icon.jpg')}" alt="{escape(name)}" width="88" height="88" loading="lazy"></span><span class="app-name">{escape(name)}</span><span class="app-desc">{escape(en if lang else pt)}</span></a>''' for slug,name,pt,en in APPS)
    guides = ''.join(
        f'<article class="app-guide"><h3>{escape(APP_GUIDES[slug][lang])}</h3>'
        f'<p>{escape(APP_GUIDES[slug][lang+2])}</p>'
        f'<a class="text-link" href="https://alvaro-menezes.com/apps/{slug}.html" target="_blank" rel="noopener noreferrer">'
        f'{t("Abrir", "Open")} {escape(name)} <span aria-hidden="true">↗</span></a></article>'
        for slug,name,pt,en in APPS)
    pillars = [
        ('01',t('A prática como ponto de partida','Built around real practice'),t('A experiência do radiologista orienta a escolha dos problemas, a organização das informações e o desenho de cada ferramenta.','Radiology experience guides the problems we address, the information we organise and the design of each tool.')),
        ('02',t('Clareza em cada interação','Clarity in every interaction'),t('Interfaces objetivas para consultar critérios e organizar cálculos, com atenção à leitura, à navegação e ao uso em diferentes telas.','Focused interfaces for consulting criteria and organising calculations, with attention to readability, navigation and different screen sizes.')),
        ('03',t('Tecnologia com responsabilidade','Responsible technology'),t('Referências, limitações e revisão profissional fazem parte do uso consciente de ferramentas digitais na saúde.','References, limitations and professional review are central to the responsible use of digital tools in healthcare.')),
    ]
    pillars_html = ''.join(f'<article class="pillar"><p class="pillar-symbol" aria-hidden="true">{i}</p><h3>{heading}</h3><p>{body}</p></article>' for i,heading,body in pillars)
    platforms = [
        ('phone','iOS',t('Experiências para iPhone e iPad, com foco em mobilidade, leitura confortável e acesso prático às ferramentas de radiologia.','Experiences for iPhone and iPad, focused on mobility, comfortable reading and practical access to radiology tools.'),t('Plataforma de desenvolvimento','Development platform')),
        ('android','Android',t('Aplicativos pensados para diferentes dispositivos, aproximando recursos médicos de uma rotina cada vez mais conectada.','Apps designed for a range of devices, bringing medical resources to an increasingly connected professional workflow.'),t('Plataforma de desenvolvimento','Development platform')),
        ('web','HTML5 · JavaScript · CSS',t('Ferramentas acessíveis diretamente pelo navegador, em computadores, tablets e celulares. Explore os aplicativos web disponíveis acima.','Tools accessible directly in your browser, on computers, tablets and phones. Explore the available web apps above.'),t('Aplicativos web disponíveis','Web apps available')),
    ]
    platforms_html = ''.join(f'<article class="platform-card">{svg(icon)}<h3>{heading}</h3><p>{body}</p><span class="status">{status}</span></article>' for icon,heading,body,status in platforms)
    faqs = [
        (t('Para quem são os aplicativos?','Who are the apps for?'),t('São direcionados a radiologistas e outros profissionais de saúde que conheçam a finalidade e as limitações de cada ferramenta. Não são um serviço de diagnóstico para pacientes.','They are intended for radiologists and other healthcare professionals familiar with each tool’s purpose and limitations. They are not a patient diagnostic service.')),
        (t('Preciso instalar alguma coisa?','Do I need to install anything?'),t('Os cinco aplicativos apresentados podem ser acessados pelo navegador. Os links abrem as páginas originais em alvaro-menezes.com, em uma nova aba.','The five featured apps are accessible in a browser. Links open their original pages on alvaro-menezes.com in a new tab.')),
        (t('Já estão na App Store e no Google Play?','Are they on the App Store and Google Play?'),t('Este site apresenta a iniciativa de desenvolvimento para iOS, Android e web. No momento, os acessos publicados aqui são às versões web. Links oficiais das lojas serão incluídos quando houver versões disponíveis.','This site presents the iOS, Android and web development initiative. Currently, the published links lead to web versions. Official store links will be added when releases are available.')),
        (t('Posso enviar exames ou dados de pacientes?','Can I send examinations or patient data?'),t('O site RadApps não possui upload, prontuário ou formulário clínico. Não envie dados identificáveis de pacientes pelo canal de contato. Consulte a política própria de cada aplicativo antes de inserir qualquer informação.','The RadApps website has no upload feature, medical record system or clinical form. Do not send identifiable patient data through the contact channel. Read each app’s own policy before entering information.')),
        (t('Como relatar um problema ou sugerir uma melhoria?','How do I report a problem or suggest an improvement?'),t(f'Escreva para <a href="mailto:{EMAIL}">{EMAIL}</a> e informe o aplicativo, o dispositivo, o navegador e os passos para reproduzir o problema, sem dados de pacientes.',f'Email <a href="mailto:{EMAIL}">{EMAIL}</a> with the app, device, browser and steps to reproduce the issue, without patient data.')),
    ]
    faq_html = ''.join(f'<details class="faq-item"><summary>{q}</summary><p>{a}</p></details>' for q,a in faqs)
    content = f'''
<section class="hero" id="inicio"><div class="container hero-inner"><div class="hero-copy"><p class="eyebrow">{t('Desenvolvimento de aplicativos médicos','Medical application development')}</p><h1>{t('Aplicativos e<br>calculadoras.','Radiology apps<br>and calculators.')}<span><em>{t('Para a radiologia.','Built for daily practice.')}</em></span></h1><p>{t('TI-RADS para tireoide, O-RADS para lesões anexiais, GFR para função renal, HepFe para ferro hepático e N-Lung para nódulos pulmonares. Ferramentas web desenvolvidas pelo radiologista Dr. Álvaro Menezes.','TI-RADS for thyroid nodules, O-RADS for adnexal lesions, GFR for kidney function, HepFe for liver iron and N-Lung for pulmonary nodules. Web tools developed by radiologist Dr. Álvaro Menezes.')}</p><div class="hero-actions"><a class="btn" href="#aplicativos">{t('Conheça os aplicativos','Explore the apps')} <span aria-hidden="true">↗</span></a><a class="btn btn-secondary" href="#sobre">{t('Sobre a RadApps','About RadApps')} <span aria-hidden="true">↓</span></a></div></div><figure class="hero-art"><img src="/assets/brand/radapps-logo.jpg" alt="RadApps — Apps for radiologists. Built for precision." width="1408" height="1408" fetchpriority="high"><figcaption>{t('Da experiência médica à tecnologia','From medical experience to technology')}</figcaption></figure></div></section>
<div class="platform-strip"><div class="container"><span class="platform-label">{t('Um ecossistema. Diferentes possibilidades.','One ecosystem. Different possibilities.')}</span><div class="platform-names"><span>{svg('phone')} iOS</span><span>{svg('android')} Android</span><span>{svg('web')} Web</span></div></div></div>
<section class="section section-alt" id="aplicativos"><div class="container"><div class="section-header"><p class="eyebrow">{t('Ferramentas','Tools')}</p><h2>{t('Calculadoras para a prática radiológica','Calculators for radiology practice')}</h2><p class="section-sub">{t('Calculadoras e ferramentas rápidas do dia a dia do laudo, rodando direto no navegador — sem precisar instalar nada.','Small calculators and tools for daily reporting, running right in the browser — no install required.')}</p></div><div class="apps-panel"><div class="apps-grid">{apps}</div></div><p class="app-note">{t('Os aplicativos abrem em alvaro-menezes.com, em uma nova aba.','Apps open on alvaro-menezes.com in a new tab.')} <a href="{url('medical',lang)}">{t('Orientações de uso','Usage guidance')} ↗</a></p><div class="app-guides">{guides}</div></div></section>
<section class="section" id="sobre"><div class="container"><div class="split-heading"><div><p class="eyebrow">{t('Sobre a RadApps','About RadApps')}</p><h2>{t('Conhecimento médico.<br><em>Experiência digital.</em>','Medical knowledge.<br><em>Digital experience.</em>')}</h2></div><p>{t('A RadApps nasce do encontro entre radiologia e desenvolvimento de software. Nosso propósito é transformar necessidades da prática em ferramentas claras, acessíveis e úteis.','RadApps brings together radiology and software development. Our purpose is to translate practical needs into clear, accessible and useful tools.')}</p></div><div class="about-grid"><figure class="banner-image"><img src="/assets/brand/radapps-banner.jpg" alt="RadApps — Apps for radiologists. Built for precision. iOS & Android. radapps.app" width="1792" height="1008" loading="lazy"></figure><div class="about-copy"><h3>{t('Criada por um radiologista.','Created by a radiologist.')}</h3><p>{t('Uma iniciativa do <strong>Dr. Álvaro Menezes</strong>, médico radiologista, Membro Titular do Colégio Brasileiro de Radiologia, com atuação em Radiologia Geral e Musculoesquelética.','An initiative by <strong>Dr. Álvaro Menezes</strong>, a radiologist and full member of the Brazilian College of Radiology, practising general and musculoskeletal radiology.')}</p><p>{t('Desenvolvimento independente, a partir de Fortaleza, Brasil, com uma linguagem visual e experiências pensadas para profissionais em diferentes lugares.','Independent development based in Fortaleza, Brazil, with a visual language and experiences designed for professionals across borders.')}</p><a class="text-link" href="https://alvaro-menezes.com/" target="_blank" rel="noopener noreferrer">{t('Conheça o fundador','Meet the founder')} <span aria-hidden="true">↗</span></a></div></div><div class="pillars">{pillars_html}</div></div></section>
<section class="section section-alt" id="plataformas"><div class="container"><div class="section-header"><p class="eyebrow">{t('Desenvolvimento multiplataforma','Cross-platform development')}</p><h2>{t('A radiologia acompanha você.','Radiology, wherever you are.')}</h2><p class="section-sub">{t('Do computador à tela do celular, projetamos experiências para diferentes formas de trabalhar, consultar e aprender.','From desktop to mobile, we design experiences for different ways of working, consulting and learning.')}</p></div><div class="platform-grid">{platforms_html}</div></div></section>
<section class="section" id="duvidas"><div class="container faq-grid"><div class="faq-heading"><p class="eyebrow">{t('Perguntas frequentes','Frequently asked questions')}</p><h2>{t('Antes de<br><em>começar.</em>','Before you<br><em>get started.</em>')}</h2><p>{t('O essencial sobre acesso, disponibilidade e uso responsável das ferramentas.','The essentials of access, availability and responsible use.')}</p></div><div>{faq_html}</div></div></section>
<section class="section contact-section" id="contato"><div class="container contact-grid"><div><p class="eyebrow">{t('Vamos conversar','Get in touch')}</p><h2>{t('Boas ideias merecem<br><em>ganhar forma.</em>','Good ideas deserve<br><em>to take shape.</em>')}</h2><p>{t('Suporte, sugestões e conversas sobre aplicativos para radiologia. Fale diretamente com o responsável pela RadApps.','Support, suggestions and conversations about radiology apps. Get in touch directly with the person behind RadApps.')}</p></div><div class="contact-links"><a class="contact-link" href="mailto:{EMAIL}"><span><small>{t('Suporte e privacidade','Support and privacy')}</small><strong>{EMAIL}</strong></span><span aria-hidden="true">↗</span></a><a class="contact-link" href="https://alvaro-menezes.com/" target="_blank" rel="noopener noreferrer"><span><small>{t('Fundador · Médico radiologista','Founder · Radiologist')}</small><strong>Dr. Álvaro Menezes</strong></span><span aria-hidden="true">↗</span></a><p class="contact-fineprint">{t('Não envie exames, laudos ou dados identificáveis de pacientes.','Please do not send examinations, reports or identifiable patient data.')}</p></div></div></section>'''
    return shell('home',lang,content)

def legal_content(page,lang):
    t = lambda pt,en: en if lang else pt
    mail = f'<a href="mailto:{EMAIL}">{EMAIL}</a>'
    sections = []
    notice = ''
    if page == 'terms':
        notice=t('Estes termos se aplicam ao site institucional radapps.app. Os aplicativos vinculados podem ter termos, políticas e instruções de uso próprios.','These terms apply to the radapps.app informational website. Linked applications may have their own terms, policies and instructions for use.')
        sections=[
            (t('1. Identificação e finalidade','1. Identity and purpose'),t(f'RadApps é o nome fantasia da iniciativa independente de desenvolvimento de aplicativos de Álvaro Menezes, com base em Fortaleza, Ceará, Brasil. Este site apresenta a iniciativa e oferece links para ferramentas de radiologia. Contato do responsável: {mail}.',f'RadApps is the trade name of Álvaro Menezes’s independent app development initiative, based in Fortaleza, Ceará, Brazil. This website introduces the initiative and links to radiology tools. Contact the operator at {mail}.')),
            (t('2. Acesso e uso adequado','2. Access and appropriate use'),t('A consulta ao site é gratuita e não exige cadastro. Use-o de forma lícita, sem tentar comprometer sua segurança, interferir em sua disponibilidade ou reproduzir conteúdo de forma enganosa. O conteúdo técnico é direcionado a profissionais de saúde capazes de avaliar sua aplicabilidade.','Browsing this website is free and does not require an account. Use it lawfully, without attempting to compromise its security, disrupt its availability or reproduce content misleadingly. Technical content is intended for healthcare professionals able to assess its applicability.')),
            (t('3. Limites do serviço','3. Scope of the service'),t('O site não presta consultas, telemedicina, diagnóstico, prescrição ou atendimento de emergência. Não recebe exames nem armazena prontuários. Não existe compra, assinatura ou contratação de serviço por esta página. Eventuais produtos pagos ou serviços futuros terão condições específicas, apresentadas antes de qualquer contratação.','This site does not provide consultations, telemedicine, diagnoses, prescriptions or emergency care. It does not receive examinations or store medical records. This page offers no checkout, subscription or service contract. Any future paid products or services will have specific conditions disclosed before purchase.')),
            (t('4. Aplicativos e links externos','4. Applications and external links'),t('Os links do catálogo abrem as páginas originais dos aplicativos em alvaro-menezes.com. A inclusão de um link não amplia a finalidade de uso, as indicações ou o status regulatório do aplicativo. Leia as instruções, referências, restrições e políticas apresentadas no destino. Páginas de terceiros podem mudar sem aviso.','Catalogue links open the apps’ original pages on alvaro-menezes.com. A listing does not extend an app’s intended purpose, indications or regulatory status. Read the instructions, references, restrictions and policies at the destination. Third-party pages may change without notice.')),
            (t('5. Propriedade intelectual','5. Intellectual property'),t('A marca, o logotipo, os textos e os elementos gráficos da RadApps são protegidos pela legislação aplicável. O acesso não transfere sua titularidade nem autoriza uso da marca que sugira associação ou endosso. Direitos de terceiros e licenças de componentes de código aberto permanecem com seus titulares. Citações e demais usos legalmente permitidos são preservados.','The RadApps brand, logo, text and graphic elements are protected under applicable law. Access does not transfer ownership or authorise brand use suggesting affiliation or endorsement. Third-party rights and open-source component licences remain with their respective holders. Quotation and other legally permitted uses are preserved.')),
            (t('6. Disponibilidade e responsabilidade','6. Availability and responsibility'),t('Buscamos manter o conteúdo correto e acessível, mas podem ocorrer erros, desatualização, interrupções e incompatibilidades. Verifique informações relevantes antes de utilizá-las. Nenhuma previsão destes termos exclui deveres ou responsabilidades que não possam ser limitados pela lei, nem afasta direitos obrigatórios do usuário ou do consumidor.','We aim to keep content accurate and accessible, but errors, outdated information, interruptions and incompatibilities may occur. Verify relevant information before relying on it. Nothing in these terms excludes duties or liabilities that cannot lawfully be limited, or removes mandatory user or consumer rights.')),
            (t('7. Alterações e legislação','7. Changes and applicable law'),t('Alterações serão publicadas nesta página com a data de atualização. Estes termos são regidos pela legislação brasileira, respeitadas as normas obrigatórias aplicáveis ao usuário e as regras legais de competência, inclusive do domicílio do consumidor quando cabíveis. As versões em português e inglês têm o mesmo propósito informativo; divergências podem ser encaminhadas ao responsável.','Changes will be published on this page with an updated date. These terms are governed by Brazilian law, subject to mandatory rules applicable to the user and statutory jurisdiction rules, including the consumer’s place of residence where applicable. Portuguese and English versions have the same informational purpose; discrepancies may be reported to the operator.')),
            (t('8. Contato','8. Contact'),t(f'Dúvidas, reclamações, correções e solicitações relacionadas ao site: {mail}.',f'Questions, complaints, corrections and requests about this website: {mail}.')),
        ]
    elif page == 'privacy':
        notice=t('Esta política descreve o site radapps.app. Ela não substitui a política de cada aplicativo, da homepage pessoal ou de outros sites abertos por seus links.','This policy describes radapps.app. It does not replace the policies of individual apps, the personal homepage or other sites opened through its links.')
        sections=[
            (t('1. Quem é o responsável','1. Who is responsible'),t(f'Álvaro Menezes é o responsável pelo site da iniciativa RadApps e pelo tratamento de dados realizado diretamente por ela. Para assuntos de privacidade e exercício de direitos, escreva para {mail}. Base de atuação: Fortaleza, Ceará, Brasil.',f'Álvaro Menezes operates the RadApps initiative’s website and is responsible for personal data processing carried out directly by it. For privacy questions and rights requests, email {mail}. Based in Fortaleza, Ceará, Brazil.')),
            (t('2. Informações tratadas','2. Information processed'),t('<ul><li><strong>Navegação:</strong> serviços de hospedagem e infraestrutura podem processar endereço IP, data e hora, página solicitada, dados do navegador e registros de falhas ou segurança para entregar e proteger o site.</li><li><strong>Preferência visual:</strong> a escolha de tema claro ou escuro é guardada no armazenamento local do navegador. O idioma é definido pela URL visitada.</li><li><strong>Contato voluntário:</strong> ao enviar um e-mail, você compartilha seu endereço, nome, conteúdo e eventuais anexos com o responsável e com os provedores de e-mail envolvidos.</li></ul><p>O site utiliza Cloudflare Web Analytics para medir visitas, páginas acessadas e desempenho, incluindo dados técnicos do navegador, dispositivo, origem do acesso e país aproximado. Segundo a Cloudflare, essa medição não utiliza cookies nem rastreia pessoas entre sites. O script é fornecido pela Cloudflare, e as métricas são enviadas à sua infraestrutura por este domínio. Não há publicidade, pixels de marketing, geolocalização precisa, formulários ou uploads. As fontes e imagens são servidas pelo próprio site. Não solicitamos dados de saúde ou de pacientes.</p>','<ul><li><strong>Browsing:</strong> hosting and infrastructure providers may process IP addresses, timestamps, requested pages, browser information and error or security logs to deliver and protect this website.</li><li><strong>Appearance preference:</strong> your light or dark theme choice is stored locally in your browser. Language is determined by the URL you visit.</li><li><strong>Voluntary contact:</strong> sending an email shares your address, name, message and any attachments with the operator and the email providers involved.</li></ul><p>This site uses Cloudflare Web Analytics to measure visits, page views and performance, including technical information about browsers, devices, referral sources and approximate country. According to Cloudflare, this measurement does not use cookies or track people across websites. Cloudflare provides the script, and metrics are sent to its infrastructure through this domain. There is no advertising, marketing pixels, precise geolocation, forms or uploads. Fonts and images are served by this site. We do not request health or patient data.</p>')),
            (t('3. Finalidades e bases legais','3. Purposes and legal bases'),t('Dados técnicos são tratados para entrega do conteúdo, prevenção de abuso, manutenção da segurança e avaliação de audiência e desempenho, com fundamento no legítimo interesse, quando aplicável e respeitados os direitos do titular. Comunicações são tratadas para responder à solicitação e, conforme o caso, para procedimentos preliminares solicitados pelo titular ou cumprimento de obrigação legal. A preferência visual serve somente à personalização solicitada. Não utilizamos o contato para campanhas de marketing não solicitadas.','Technical data is processed to deliver content, prevent abuse, maintain security and assess audience and performance, on the basis of legitimate interests where applicable and subject to data subjects’ rights. Communications are processed to respond to requests and, as appropriate, take requested pre-contractual steps or meet legal obligations. The appearance preference serves only the requested personalisation. We do not use contact information for unsolicited marketing campaigns.')),
            (t('4. Infraestrutura e compartilhamento','4. Infrastructure and sharing'),t('O site é hospedado no GitHub Pages; o domínio, o DNS, a distribuição de conteúdo (CDN), a proteção do tráfego e a medição de audiência e desempenho são gerenciados pela Cloudflare. Esses fornecedores podem tratar dados técnicos conforme suas funções e políticas. O envio de e-mail envolve o provedor de e-mail escolhido pelo visitante e o do destinatário. Dados também podem ser fornecidos quando houver obrigação legal ou ordem válida. A RadApps não vende dados pessoais.','This site is hosted on GitHub Pages; its domain, DNS, content delivery (CDN), traffic protection and audience and performance measurement are managed by Cloudflare. These providers may process technical data according to their roles and policies. Email involves both the visitor’s chosen email provider and the recipient’s provider. Data may also be disclosed to meet a legal obligation or valid order. RadApps does not sell personal data.') + ' <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" target="_blank" rel="noopener noreferrer">GitHub Privacy Statement ↗</a> · <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noopener noreferrer">Cloudflare Privacy Policy ↗</a> · <a href="https://www.cloudflare.com/web-analytics/" target="_blank" rel="noopener noreferrer">Cloudflare Web Analytics ↗</a>'),
            (t('5. Transferências internacionais','5. International transfers'),t('A infraestrutura de fornecedores globais pode envolver tratamento de dados fora do Brasil. Essas operações se sujeitam às regras aplicáveis de proteção de dados e aos mecanismos de transferência previstos nos instrumentos e nas políticas dos fornecedores. Informações sobre os fornecedores e as operações relacionadas ao site podem ser solicitadas pelo canal de privacidade.','Global providers’ infrastructure may involve processing outside Brazil. Such operations are subject to applicable data protection rules and the transfer mechanisms described in providers’ agreements and policies. Information about providers and website-related processing may be requested through the privacy contact.')),
            (t('6. Conservação e segurança','6. Retention and security'),t('A preferência de tema permanece no dispositivo até ser removida pelo usuário. E-mails são mantidos pelo tempo necessário ao atendimento da solicitação e à eventual proteção de direitos ou cumprimento de obrigação legal; a necessidade de conservação é reavaliada após o encerramento do assunto. Registros de infraestrutura e métricas de audiência seguem as regras de retenção dos respectivos fornecedores. Utilizamos HTTPS e limitamos o site a funções institucionais. Nenhuma transmissão ou sistema oferece segurança absoluta.','The theme preference remains on the device until you remove it. Emails are retained as needed to address the request and, where necessary, protect rights or meet legal obligations; continued retention is reassessed after the matter is closed. Infrastructure logs and audience metrics follow the respective providers’ retention rules. We use HTTPS and restrict the website to informational functions. No transmission or system can provide absolute security.')),
            (t('7. Seus direitos','7. Your rights'),t(f'Nos termos da legislação aplicável, você pode solicitar confirmação e acesso, correção, informações sobre compartilhamento e, quando cabível, anonimização, bloqueio, eliminação, portabilidade, oposição ao tratamento e revogação de consentimento. Envie a solicitação para {mail}. Poderemos pedir apenas os dados necessários para confirmar a identidade e atender com segurança, nos prazos legais aplicáveis. Você também pode apresentar petição à Autoridade Nacional de Proteção de Dados (ANPD).',f'Under applicable law, you may request confirmation and access, correction, information about sharing and, where applicable, anonymisation, restriction, erasure, portability, objection and withdrawal of consent. Send requests to {mail}. We may request only the information necessary to verify identity and respond securely, within applicable statutory time limits. You may also submit a petition to Brazil’s National Data Protection Authority (ANPD).')),
            (t('8. Crianças, pacientes e outros sites','8. Children, patients and other sites'),t('O conteúdo é direcionado a profissionais, não a crianças. Não solicitamos dados de menores nem informações clínicas identificáveis. Caso esses dados sejam enviados por engano, entre em contato para avaliação e remoção, ressalvadas obrigações legais. Ao sair deste domínio, consulte a política do destino antes de inserir dados.','Content is intended for professionals, not children. We do not request children’s data or identifiable clinical information. If such information is sent in error, contact us for review and removal, subject to legal obligations. When leaving this domain, read the destination’s policy before entering data.')),
            (t('9. Atualizações e referência','9. Updates and reference'),t('Esta política será revista quando as práticas do site mudarem. A data no topo identifica a versão publicada. Referência:','This policy will be revised when website practices change. The date at the top identifies the published version. Reference:') + ' <a href="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm" target="_blank" rel="noopener noreferrer">Lei Geral de Proteção de Dados — LGPD ↗</a>.'),
        ]
    elif page == 'cookies':
        sections=[
            (t('1. Como este site funciona','1. How this site works'),t('A RadApps utiliza Cloudflare Web Analytics para estatísticas de visitas e desempenho, sem cookies de análise de audiência, conforme a documentação do serviço. O site não define cookies de publicidade. Não há banner de consentimento para marketing porque o site não implementa esse tratamento. Serviços de infraestrutura podem processar informações técnicas ou empregar mecanismos necessários à segurança, conforme sua configuração e políticas.','RadApps uses Cloudflare Web Analytics for visit and performance statistics, without audience analytics cookies, according to the service documentation. The site does not set advertising cookies. There is no marketing consent banner because the site does not implement that processing. Infrastructure services may process technical information or use mechanisms necessary for security, according to their configuration and policies.')),
            (t('2. Tema claro ou escuro','2. Light or dark theme'),t('Ao escolher um tema, o navegador guarda a chave <code>radapps-theme</code> no localStorage, com o valor <code>light</code> ou <code>dark</code>. Essa informação não contém identificador de visitante, não é enviada por nosso código a um servidor e permanece até ser apagada. Se você não escolher um tema, o site acompanha a configuração do dispositivo.','When you choose a theme, your browser stores the <code>radapps-theme</code> key in localStorage, with the value <code>light</code> or <code>dark</code>. This contains no visitor identifier, is not sent by our code to a server and remains until removed. If you do not choose a theme, the site follows your device setting.')),
            (t('3. Idioma','3. Language'),t('As páginas em inglês usam o caminho <code>/en/</code>. A navegação preserva o idioma selecionado por meio dos links, sem precisar de cookie ou perfil pessoal.','English pages use the <code>/en/</code> path. Navigation preserves your chosen language through links, without a cookie or personal profile.')),
            (t('4. Gerencie sua preferência','4. Manage your preference'),t('Você pode remover a preferência visual pelo botão abaixo ou apagar os dados de radapps.app nas configurações do navegador. Isso não apaga informações de outros sites ou dos aplicativos vinculados.','You can remove the appearance preference with the button below or delete radapps.app data in your browser settings. This does not erase information from other websites or linked apps.') + f'<p><button type="button" class="preferences-reset" id="reset-preferences">{t("Restaurar tema do dispositivo","Restore device theme")}</button></p><p class="reset-status" id="reset-status" role="status"></p>'),
            (t('5. Mudanças e referência','5. Changes and reference'),t('Se recursos opcionais de rastreamento forem adotados no futuro, esta política e os controles apropriados deverão ser atualizados antes da sua ativação. Consulte também a','If optional tracking features are introduced in the future, this policy and appropriate controls must be updated before activation. See also the') + f' <a href="{url("privacy",lang)}">{title("privacy",lang)}</a>. ' + '<a href="https://www.gov.br/anpd/pt-br/centrais-de-conteudo/materiais-educativos-e-publicacoes/guia_orientativo_cookies_e_protecao_de_dados_pessoais" target="_blank" rel="noopener noreferrer">ANPD — Cookies e proteção de dados pessoais ↗</a>.'),
        ]
    elif page == 'medical':
        notice=t('A presença de um aplicativo neste catálogo não comprova certificação, registro sanitário, validação clínica ou autorização para uma finalidade específica.','An app’s presence in this catalogue is not evidence of certification, regulatory clearance, clinical validation or authorisation for a specific purpose.')
        sections=[
            (t('1. Informação para profissionais','1. Information for professionals'),t('A RadApps apresenta ferramentas de referência voltadas a profissionais de saúde. Este site institucional não avalia pacientes, imagens ou exames e não fornece diagnóstico, prescrição ou tratamento individualizado.','RadApps presents reference tools intended for healthcare professionals. This informational website does not assess patients, images or examinations and does not provide individual diagnoses, prescriptions or treatment.')),
            (t('2. Confira antes de utilizar','2. Check before use'),t('Antes de usar qualquer aplicativo, confira sua finalidade, população-alvo, versão, unidades, critérios de exclusão, referências e limitações. Revise as entradas e os resultados à luz das diretrizes atualizadas e do contexto clínico. Calculadoras e classificações podem produzir resultados inadequados quando aplicadas fora de seu escopo.','Before using any app, check its intended purpose, target population, version, units, exclusions, references and limitations. Review inputs and outputs against current guidance and clinical context. Calculators and classifications can produce inappropriate results when used outside their scope.')),
            (t('3. Julgamento clínico e responsabilidade','3. Clinical judgment and responsibility'),t('Resultados não devem fundamentar, isoladamente, diagnóstico, tratamento ou decisões urgentes. O profissional deve exercer julgamento independente e utilizar ferramentas apropriadas e autorizadas para a finalidade pretendida. Este aviso não elimina obrigações legais do desenvolvedor nem substitui os requisitos de segurança e desempenho de cada produto.','Results must not be the sole basis for diagnosis, treatment or urgent decisions. Professionals must exercise independent judgment and use tools appropriate and authorised for the intended purpose. This notice does not remove the developer’s legal obligations or replace each product’s safety and performance requirements.')),
            (t('4. Situação regulatória','4. Regulatory status'),t('A qualificação de um software como dispositivo médico depende, entre outros fatores, de sua finalidade e funcionalidades. A existência de um aviso educacional não dispensa requisitos regulatórios eventualmente aplicáveis. Verifique as informações oficiais e específicas de cada produto. Este site não declara aprovação pela Anvisa, FDA, marcação CE ou endosso por sociedades médicas.','Whether software qualifies as a medical device depends, among other factors, on its intended purpose and functions. An educational disclaimer does not waive applicable regulatory requirements. Check official, product-specific information. This site does not claim Anvisa or FDA approval, CE marking or endorsement by medical societies.') + ' <a href="https://www.gov.br/anvisa/pt-br/centraisdeconteudo/publicacoes/produtos-para-a-saude/manuais/software-como-dispositivo-medico-perguntas-e-respostas" target="_blank" rel="noopener noreferrer">Anvisa — Software como Dispositivo Médico ↗</a>.'),
            (t('5. Privacidade e emergência','5. Privacy and emergencies'),t('Não envie dados identificáveis, exames ou laudos de pacientes pelos canais institucionais da RadApps. O contato do site não é monitorado como serviço de emergência. Em uma situação de urgência, procure o serviço de emergência local.','Do not send identifiable patient data, examinations or reports through RadApps institutional channels. The website contact is not monitored as an emergency service. In an emergency, contact your local emergency service.')),
            (t('6. Comunicação de problemas','6. Reporting issues'),t(f'Se identificar erro, resultado inesperado ou referência desatualizada, interrompa o uso daquela informação e relate o problema a {mail}, sem incluir dados pessoais ou clínicos identificáveis.',f'If you identify an error, unexpected result or outdated reference, stop relying on that information and report the issue to {mail}, without identifiable personal or clinical data.')),
        ]
    elif page == 'accessibility':
        sections=[
            (t('1. Nosso compromisso','1. Our commitment'),t('Buscamos tornar o site acessível em diferentes dispositivos e formas de navegação. Esta declaração descreve recursos implementados e não constitui certificação de conformidade integral.','We aim to make this site accessible across devices and ways of navigating. This statement describes implemented features and is not a certification of full conformance.')),
            (t('2. Recursos disponíveis','2. Available features'),t('<ul><li>Navegação por teclado, indicação visual de foco e link para pular ao conteúdo.</li><li>Textos estruturados por títulos, descrições de imagens e controles identificados.</li><li>Versões em português e inglês, com idioma indicado no documento.</li><li>Temas claro e escuro, layout responsivo e respeito à preferência por movimento reduzido.</li><li>Páginas de conteúdo legíveis sem JavaScript; a alternância de tema e o menu compacto dependem dele.</li></ul>','<ul><li>Keyboard navigation, visible focus and a skip-to-content link.</li><li>Structured headings, image descriptions and labelled controls.</li><li>Portuguese and English versions with document language declared.</li><li>Light and dark themes, responsive layout and respect for reduced-motion preferences.</li><li>Content pages readable without JavaScript; theme switching and the compact menu depend on it.</li></ul>')),
            (t('3. Limitações e melhorias','3. Limitations and improvements'),t('As artes originais da marca contêm textos em inglês dentro das imagens; suas descrições alternativas identificam a marca e a mensagem. Os aplicativos vinculados possuem interfaces próprias e não estão cobertos por esta declaração. Compatibilidade pode variar entre navegadores e tecnologias assistivas.','Original brand artwork includes English text embedded in images; alternative descriptions identify the brand and message. Linked apps have their own interfaces and are not covered by this statement. Compatibility may vary between browsers and assistive technologies.')),
            (t('4. Relate uma barreira','4. Report a barrier'),t(f'Se encontrar dificuldade, entre em contato por {mail}. Informe a página, o dispositivo, o navegador e, se desejar, a tecnologia assistiva utilizada. Não inclua dados de pacientes.',f'If you encounter a difficulty, contact {mail}. Include the page, device, browser and, if you wish, the assistive technology used. Do not include patient data.')),
        ]
    content = (f'<p class="notice">{notice}</p>' if notice else '')
    for heading,body in sections:
        if body.startswith('<ul>'):
            markup = body
        elif '<p>' in body:
            lead, rest = body.split('<p>', 1)
            markup = f'<p>{lead}</p><p>{rest}'
        else:
            markup = f'<p>{body}</p>'
        content += f'<section><h2>{heading}</h2>{markup}</section>'
    return content

def legal_page(page,lang):
    t = lambda pt,en: en if lang else pt
    nav = ''.join(f'<a href="{url(key,lang)}" {"aria-current=page" if key==page else ""}>{title(key,lang)}</a>' for key in PAGES if key != 'home')
    content = f'''<header class="legal-hero"><div class="container"><p class="eyebrow">{t('Transparência e responsabilidade','Transparency and responsibility')}</p><h1>{title(page,lang)}</h1><p>{t('Atualizado em 17 de setembro de 2026','Last updated September 17, 2026')} · radapps.app</p></div></header><div class="container legal-layout"><nav class="legal-nav" aria-label="{t('Páginas legais','Legal pages')}">{nav}<a href="{url('home',lang)}">← {t('Voltar para a RadApps','Back to RadApps')}</a></nav><article class="prose">{legal_content(page,lang)}</article></div>'''
    return shell(page,lang,content,LEGAL_DESCRIPTIONS[page][lang])

def main():
    for lang in (0,1):
        for page in PAGES:
            path = ROOT / url(page,lang).lstrip('/') / 'index.html'
            path.parent.mkdir(parents=True,exist_ok=True)
            path.write_text(homepage(lang) if page=='home' else legal_page(page,lang))
    missing = '<section class="container not-found"><p class="eyebrow">404</p><h1>Página não encontrada.<br><em>Page not found.</em></h1><p>O endereço pode ter mudado. / The address may have changed.</p><a class="btn" href="/">Voltar à RadApps / Back to RadApps ↗</a></section>'
    (ROOT/'404.html').write_text(shell('home',0,missing,not_found=True))
    locations = [DOMAIN + url(page,lang) for page in PAGES for lang in (0,1)]
    entries = []
    for page in PAGES:
        alternates = ''.join(f'<xhtml:link rel="alternate" hreflang="{code}" href="{DOMAIN}{url(page,lang)}"/>' for code,lang in [('pt-BR',0),('en',1),('x-default',0)])
        for lang in (0,1):
            entries.append(f'  <url><loc>{DOMAIN}{url(page,lang)}</loc><lastmod>{PAGE_MODIFIED.get(page, DATE)}</lastmod>{alternates}</url>')
    (ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'+'\n'.join(entries)+'\n</urlset>\n')
    (ROOT/'robots.txt').write_text(f'User-agent: *\nAllow: /\nDisallow: /scripts/\nDisallow: /docs/\nSitemap: {DOMAIN}/sitemap.xml\n')
    print(f'Built {len(locations)} pages + 404. Assets versioned with SHA-256.')

if __name__ == '__main__':
    main()
